import type { TierAccordionCard } from "@/components/tiers/tier-accordion-list";
import type { Locale } from "@/lib/i18n/config";
import type { Tier } from "@/lib/types";

type LocalizedTier = Pick<TierAccordionCard, "label" | "level" | "teaser" | "description" | "statusBadge" | "noteBadge" | "sections">;

const en: Record<Tier, LocalizedTier> = {
  tier_1: { label: "Sputnik", level: "Basic access", teaser: "Your first step into Lumina's private world, with early access and exclusive extras.", description: "A gentle way to get closer and see more than what appears on public social media.", noteBadge: "START HERE", sections: [{ title: "Included", label: "early access", icon: "star", items: ["Early access to photos and videos", "Behind-the-scenes updates and previews", "Extra shots not shared publicly", "Character lore and project notes"] }] },
  tier_2: { label: "Insider", level: "Extended access", teaser: "More of the creative process, more backstage moments and a closer connection.", description: "Follow each concept from the first idea to the final result.", noteBadge: "INNER CIRCLE", sections: [{ title: "Included", label: "core access", icon: "spark", items: ["Everything in Sputnik", "Private Telegram messages", "Members-only polls", "Stream recordings and more backstage content"] }, { title: "Monthly extras", label: "monthly drops", icon: "gift", items: ["Bonus content", "Phone wallpapers", "Custom AI art", "One content request each month"] }] },
  tier_3: { label: "VIP", level: "Premium access", teaser: "More personal attention, private photos and videos, and special updates.", description: "For members who want the closest experience and the strongest voice in future projects.", statusBadge: "RECOMMENDED", noteBadge: "MOST POPULAR", sections: [{ title: "Included", label: "premium access", icon: "crown", items: ["Everything in previous plans", "Exclusive mini-series and sketches", "Voice messages and gaming sessions", "Personal wishes and greetings"] }, { title: "Shape the project", label: "priority vote", icon: "vote", items: ["Priority in polls", "More requested content", "Suggest ideas for future stories", "Priority member status"] }] },
  tier_4: { label: "After Dark", level: "Most private access", teaser: "Lumina's boldest, darkest and most private side.", description: "A rare format that never reaches the public feed.", statusBadge: "UNLOCK THE DARK SIDE", noteBadge: "EXCLUSIVE ACCESS", sections: [{ title: "Private archive", label: "restricted archive", icon: "moon", items: ["All pole-dance content", "Training photos and videos", "Choreography and routines", "Classroom backstage moments", "Training preparation", "Progress from the first lesson", "Outtakes and funny moments", "Exclusive edits"] }, { title: "Bolder content", label: "uncut archive", icon: "flame", items: ["Bolder photo sets and looks", "Extra material from shoots", "Exclusive backstage videos"] }, { title: "Progress diary", label: "private process", icon: "diamond", items: ["A personal pole journey", "Goals, milestones and results", "Routine preparation", "Practice and everything left off camera"] }, { title: "Status", label: "night rank", icon: "status", items: ["Dark VIP community status", "Highest priority across all plans", "Earliest project announcements", "Access to future experimental formats", "Cosplay and pole content"] }] }
};

const vi: Record<Tier, LocalizedTier> = {
  tier_1: { label: "Sputnik", level: "Quyền truy cập cơ bản", teaser: "Bước đầu để khám phá thế giới riêng của Lumina, xem sớm và nhận thêm nội dung độc quyền.", description: "Một cách nhẹ nhàng để đến gần Lumina hơn và xem những điều không có trên mạng xã hội.", noteBadge: "BẮT ĐẦU TỪ ĐÂY", sections: [{ title: "Quyền lợi", label: "xem sớm", icon: "star", items: ["Xem ảnh và video sớm", "Hậu trường và nội dung hé lộ", "Ảnh bổ sung không đăng công khai", "Câu chuyện nhân vật và ghi chú dự án"] }] },
  tier_2: { label: "Insider", level: "Quyền truy cập mở rộng", teaser: "Theo dõi sâu hơn quá trình sáng tạo, hậu trường và những khoảnh khắc gần gũi hơn.", description: "Đồng hành cùng mỗi concept từ ý tưởng đầu tiên đến thành phẩm.", noteBadge: "INNER CIRCLE", sections: [{ title: "Quyền lợi", label: "nội dung chính", icon: "spark", items: ["Toàn bộ quyền lợi của Sputnik", "Nhắn tin riêng qua Telegram", "Tham gia bình chọn riêng", "Xem lại livestream và nhiều hậu trường hơn"] }, { title: "Quà mỗi tháng", label: "quà hằng tháng", icon: "gift", items: ["Nội dung bonus", "Hình nền điện thoại", "AI art theo yêu cầu", "Một yêu cầu nội dung mỗi tháng"] }] },
  tier_3: { label: "VIP", level: "Quyền truy cập cao cấp", teaser: "Nhiều tương tác riêng hơn, ảnh và video độc quyền cùng các cập nhật đặc biệt.", description: "Dành cho người muốn trải nghiệm gần gũi nhất và có tiếng nói trong các dự án sắp tới.", statusBadge: "ĐỀ XUẤT", noteBadge: "ĐƯỢC CHỌN NHIỀU", sections: [{ title: "Quyền lợi", label: "quyền lợi VIP", icon: "crown", items: ["Toàn bộ quyền lợi của các gói trước", "Mini-series và sketch độc quyền", "Tin nhắn thoại và chơi game cùng nhau", "Lời chúc và nội dung cá nhân"] }, { title: "Cùng tạo nên dự án", label: "ưu tiên bình chọn", icon: "vote", items: ["Ưu tiên trong các cuộc bình chọn", "Nhiều nội dung theo yêu cầu hơn", "Đề xuất ý tưởng cho câu chuyện mới", "Ưu tiên dành cho thành viên VIP"] }] },
  tier_4: { label: "After Dark", level: "Quyền truy cập riêng tư nhất", teaser: "Góc táo bạo, bí ẩn và riêng tư nhất của Lumina.", description: "Những nội dung hiếm có, không xuất hiện trên trang công khai.", statusBadge: "MỞ KHÓA DARK SIDE", noteBadge: "QUYỀN TRUY CẬP ĐỘC QUYỀN", sections: [{ title: "Kho nội dung riêng", label: "kho riêng", icon: "moon", items: ["Toàn bộ nội dung pole dance", "Ảnh và video tập luyện", "Các tổ hợp động tác và bài diễn", "Hậu trường buổi tập", "Chuẩn bị trước khi tập", "Hành trình tiến bộ từ buổi đầu", "Khoảnh khắc lỗi và vui nhộn", "Video edit độc quyền"] }, { title: "Nội dung táo bạo hơn", label: "không cắt", icon: "flame", items: ["Bộ ảnh và concept táo bạo hơn", "Nội dung bổ sung từ buổi chụp", "Video hậu trường độc quyền"] }, { title: "Nhật ký tiến bộ", label: "hành trình riêng", icon: "diamond", items: ["Hành trình học pole của Lumina", "Mục tiêu, cột mốc và kết quả", "Chuẩn bị bài diễn", "Luyện động tác và những điều chưa từng lên sóng"] }, { title: "Đặc quyền", label: "night rank", icon: "status", items: ["Danh hiệu Dark VIP trong cộng đồng", "Mức ưu tiên cao nhất", "Nhận thông báo dự án sớm nhất", "Trải nghiệm các format mới trong tương lai", "Cosplay kết hợp pole"] }] }
};

export function localizeTierCards(cards: TierAccordionCard[], locale: Locale) {
  if (locale === "ru") return cards;
  const dictionary = locale === "vi" ? vi : en;
  return cards.map((card) => ({
    ...card,
    ...dictionary[card.tier],
    price: card.price.replace(/\s*\/\s*месяц/i, locale === "vi" ? " / tháng" : " / month")
  }));
}
